// src/pages/Marketplace/Sell/constants/productNames.js
// ============================================================
// COMMON NIGERIAN FOOD PRODUCT NAMES
// ============================================================

export const productNames = [
    // ==========================================================
    // 1. RICE PRODUCTS
    // ==========================================================
    'Mama Gold Rice',
    'Royal Stallion Rice',
    'Abakaliki Rice',
    'Ofada Rice',
    'Basmati Rice',
    'Parboiled Rice',
    'White Rice',
    'Brown Rice',
    'Long Grain Rice',
    'Short Grain Rice',
    'Jasmine Rice',
    'Thai Rice',
    'Local Rice',
    'Ebonyi Rice',
    'Benue Rice',
    'Kebbi Rice',
    'Rice Flour',
    'Rice Noodles',
    'Rice Cakes',
    'Rice Crisps',
    'Sushi Rice',
    'Arborio Rice',
    'Risotto Rice',
    'Glutinous Rice',
    'Local White Rice',
    'Premium Basmati Rice',
    'Extra Long Grain Rice',
    'Organic Rice',
    'Brown Basmati Rice',
    'Parboiled Basmati Rice',

    // ==========================================================
    // 2. BEANS & LEGUMES
    // ==========================================================
    'Honey Beans',
    'Brown Beans',
    'Black Beans',
    'Kidney Beans',
    'Pinto Beans',
    'Navy Beans',
    'White Beans',
    'Red Beans',
    'Mottled Beans',
    'Cream Beans',
    'Soya Beans',
    'Cowpea',
    'White Cowpea',
    'Brown Cowpea',
    'Pigeon Peas',
    'Lentils',
    'Green Lentils',
    'Brown Lentils',
    'Red Lentils',
    'Split Peas',
    'Chickpeas',
    'Garbanzo Beans',
    'Bambara Nut',
    'Oloyin Beans',
    'Kafio Beans',
    'Beans Flour',
    'Beans Chunks',
    'Fermented Beans',
    'Boiled Beans',
    'Soy Chunks',
    'Soy Flour',
    'Soy Milk',

    // ==========================================================
    // 3. GARRI & CASSAVA PRODUCTS
    // ==========================================================
    'Ijebu Garri',
    'White Garri',
    'Yellow Garri',
    'Benue Garri',
    'Eba (Garri)',
    'Cassava Flour',
    'Cassava Starch',
    'Tapioca',
    'Cassava Chips',
    'Cassava Fufu',
    'Lafun',
    'Cassava Porridge',
    'Cassava Bread',
    'Garri Flour',
    'Instant Garri',

    // ==========================================================
    // 4. YAM & TUBERS
    // ==========================================================
    'White Yam',
    'Yellow Yam',
    'Water Yam',
    'Aerial Yam',
    'Bitter Yam',
    'Puna Yam',
    'Bobo Yam',
    'Ghana Yam',
    'Pounded Yam',
    'Yam Flour',
    'Pounded Yam Flour',
    'Yam Chips',
    'Yam Pottage',
    'Dun Dun (Fried Yam)',
    'Yam Porridge',

    // ==========================================================
    // 5. SWEET POTATO & OTHER TUBERS
    // ==========================================================
    'White Sweet Potato',
    'Yellow Sweet Potato',
    'Purple Sweet Potato',
    'Sweet Potato Flour',
    'Cocoyam',
    'Taro',
    'Red Cocoyam',
    'White Cocoyam',
    'Irish Potato',
    'Red Irish Potato',
    'White Irish Potato',
    'Tiger Nut',
    'Tigernut',
    'Tigernut Flour',
    'Tigernut Milk',

    // ==========================================================
    // 6. OILS & FATS
    // ==========================================================
    'Red Palm Oil',
    'Unrefined Palm Oil',
    'Refined Palm Oil',
    'Local Palm Oil',
    'Premium Palm Oil',
    'Groundnut Oil',
    'Unrefined Groundnut Oil',
    'Refined Groundnut Oil',
    'Pure Groundnut Oil',
    'Vegetable Oil',
    'Pure Vegetable Oil',
    'Refined Vegetable Oil',
    'Coconut Oil',
    'Virgin Coconut Oil',
    'Refined Coconut Oil',
    'Extra Virgin Coconut Oil',
    'Olive Oil',
    'Extra Virgin Olive Oil',
    'Virgin Olive Oil',
    'Sunflower Oil',
    'Palm Kernel Oil',
    'Sesame Oil',
    'Soybean Oil',
    'Corn Oil',
    'Canola Oil',
    'Peanut Oil',
    'Shea Butter',
    'Unrefined Shea Butter',
    'Refined Shea Butter',
    'Palm Margarine',
    'Vegetable Margarine',
    'Butter',
    'Ghee',
    'Coconut Cream',
    'Palm Cream',

    // ==========================================================
    // 7. SPICES & SEASONINGS
    // ==========================================================
    'Dried Crayfish',
    'Ground Crayfish',
    'Crayfish Powder',
    'Ogiri',
    'Ogiri (Melon)',
    'Ogiri (Locust Bean)',
    'Iru (Locust Bean)',
    'Iru (Fermented)',
    'Iru (Dried)',
    'Dry Pepper',
    'Pepper Powder',
    'Ground Pepper',
    'Fresh Pepper',
    'Rodo (Fresh Pepper)',
    'Knorr Cube',
    'Maggi Cube',
    'Royco Cube',
    'Seasoning Cube',
    'Seasoning Powder',
    'Knorr Powder',
    'Maggi Powder',
    'Royco Powder',
    'Curry Powder',
    'Yellow Curry',
    'Spicy Curry',
    'Thyme',
    'Dried Thyme',
    'Fresh Thyme',
    'Thyme Powder',
    'Nutmeg',
    'Fresh Nutmeg',
    'Ground Nutmeg',
    'Nutmeg Powder',
    'Cinnamon',
    'Cinnamon Stick',
    'Ground Cinnamon',
    'Cinnamon Powder',
    'Cloves',
    'Whole Cloves',
    'Ground Cloves',
    'Clove Powder',
    'Ginger Powder',
    'Dried Ginger',
    'Ground Ginger',
    'Fresh Ginger Powder',
    'Garlic Powder',
    'Dried Garlic',
    'Ground Garlic',
    'Granulated Garlic',
    'Turmeric',
    'Fresh Turmeric',
    'Ground Turmeric',
    'Turmeric Powder',
    'Paprika',
    'Sweet Paprika',
    'Hot Paprika',
    'Smoked Paprika',
    'Paprika Powder',
    'Bay Leaves',
    'Dried Bay Leaves',
    'Fresh Bay Leaves',
    'Oregano',
    'Dried Oregano',
    'Fresh Oregano',
    'Oregano Powder',
    'Basil',
    'Fresh Basil',
    'Dried Basil',
    'Basil Powder',
    'Sage',
    'Dried Sage',
    'Fresh Sage',
    'Sage Powder',
    'Rosemary',
    'Dried Rosemary',
    'Fresh Rosemary',
    'Rosemary Powder',
    'Mint',
    'Fresh Mint',
    'Dried Mint',
    'Mint Powder',
    'Parsley',
    'Fresh Parsley',
    'Dried Parsley',
    'Parsley Flakes',
    'Coriander',
    'Fresh Coriander',
    'Dried Coriander',
    'Coriander Powder',
    'Cumin',
    'Cumin Seeds',
    'Ground Cumin',
    'Cumin Powder',
    'Cardamom',
    'Green Cardamom',
    'Black Cardamom',
    'Cardamom Powder',
    'Allspice',
    'Allspice Powder',
    'Saffron',
    'Saffron Threads',
    'Saffron Powder',
    'Vanilla',
    'Vanilla Beans',
    'Vanilla Extract',
    'Vanilla Powder',
    'Tamarind',
    'Tamarind Paste',
    'Tamarind Concentrate',
    'Lemon Grass',
    'Fresh Lemon Grass',
    'Dried Lemon Grass',
    'Scent Leaf',
    'Scent Leaves',
    'Nchanwu',
    'Efirin',
    'African Basil',
    'Bitter Leaf (Dry)',
    'Dried Bitter Leaf',
    'Bitter Leaf Powder',
    'Uziza Leaves',
    'Uziza',

    // ==========================================================
    // 8. MEAT & PROTEIN
    // ==========================================================
    'Fresh Beef',
    'Beef (Lean)',
    'Beef (Fatty)',
    'Beef (Stewing)',
    'Beef (Ground)',
    'Beef Mince',
    'Fresh Goat Meat',
    'Goat Meat (Young)',
    'Goat Meat (Mature)',
    'Fresh Chicken',
    'Broiler Chicken',
    'Local Chicken',
    'Free Range Chicken',
    'Chicken (Whole)',
    'Chicken (Breast)',
    'Chicken (Thigh)',
    'Chicken (Wing)',
    'Chicken (Leg)',
    'Chicken (Drumstick)',
    'Chicken (Gizzard)',
    'Chicken (Liver)',
    'Chicken (Heart)',
    'Fresh Turkey',
    'Turkey (Whole)',
    'Turkey (Breast)',
    'Turkey (Thigh)',
    'Turkey (Wing)',
    'Fresh Duck',
    'Duck (Whole)',
    'Duck (Breast)',
    'Fresh Pork',
    'Pork (Lean)',
    'Pork (Fatty)',
    'Pork (Chops)',
    'Pork (Belly)',
    'Fresh Ram',
    'Ram Meat',
    'Mutton',
    'Fresh Rabbit',
    'Bushmeat',
    'Grasscutter',
    'Cane Rat',
    'Antelope',
    'Deer Meat',
    'Squirrel Meat',
    'Goat Head',
    'Beef Bones',
    'Cow Legs',
    'Cow Tongue',
    'Beef Tripe',
    'Beef Liver',
    'Beef Kidney',
    'Beef Heart',
    'Beef Tongue',
    'Cow Tail',
    'Chicken Feet',
    'Pork Skin',
    'Pig Trotters',

    // ==========================================================
    // 9. FISH & SEAFOOD
    // ==========================================================
    'Fresh Tilapia',
    'Smoked Tilapia',
    'Dried Tilapia',
    'Fresh Catfish',
    'Smoked Catfish',
    'Dried Catfish',
    'Fresh Mackerel',
    'Smoked Mackerel',
    'Dried Mackerel',
    'Fresh Croaker',
    'Smoked Croaker',
    'Fresh Snapper',
    'Red Snapper',
    'Smoked Snapper',
    'Barracuda',
    'Grouper',
    'Sea Bass',
    'Fresh Tuna',
    'Sardines',
    'Herring',
    'Anchovies',
    'Stockfish (Whole)',
    'Stockfish (Head)',
    'Stockfish (Tail)',
    'Stockfish (Flakes)',
    'Fresh Prawns',
    'Dried Prawns',
    'King Prawns',
    'Fresh Shrimps',
    'Dried Shrimps',
    'Pink Shrimps',
    'Giant Snails',
    'Small Snails',
    'Snail Meat',
    'Lobster',
    'Crab',
    'Periwinkle',
    'Oysters',
    'Clams',
    'Mussels',
    'Scallops',
    'Squid',
    'Octopus',
    'Fish Roe',
    'Fish Head',

    // ==========================================================
    // 10. VEGETABLES & LEAVES
    // ==========================================================
    'Ugu (Pumpkin Leaves)',
    'Ugwu Leaves',
    'Fresh Pumpkin Leaves',
    'Efo (Amaranth)',
    'Amaranth Greens',
    'Green Amaranth',
    'Red Amaranth',
    'Waterleaf',
    'Water Leaf',
    'Bitter Leaf',
    'Bitter Leaves',
    'Ewuro',
    'African Spinach',
    'Egyptian Spinach',
    'Spinach',
    'Lettuce',
    'Green Cabbage',
    'Red Cabbage',
    'Savoy Cabbage',
    'Celery',
    'Celery Sticks',
    'Celery Leaves',
    'Okra',
    'Okoro',
    'Lady Fingers',
    'Fresh Okra',
    'Dried Okra',
    'Red Bell Pepper',
    'Green Bell Pepper',
    'Yellow Bell Pepper',
    'Tatashe',
    'Fresh Tomatoes',
    'Cherry Tomatoes',
    'Plum Tomatoes',
    'Beef Tomatoes',
    'Red Onion',
    'White Onion',
    'Yellow Onion',
    'Sweet Onion',
    'Spring Onion',
    'Green Onions',
    'Scallions',
    'Shallots',
    'Fresh Garlic',
    'Garlic Cloves',
    'Fresh Ginger',
    'Ginger Rhizome',
    'Garden Egg',
    'Garden Eggs',
    'African Eggplant',
    'White Garden Egg',
    'Green Garden Egg',
    'Yellow Eggplant',
    'Purple Eggplant',
    'Fresh Carrots',
    'Baby Carrots',
    'Organic Carrots',
    'Fresh Cucumber',
    'English Cucumber',
    'Local Cucumber',
    'Fresh Mushroom',
    'Dried Mushroom',
    'Oyster Mushroom',
    'Button Mushroom',
    'Broccoli',
    'Cauliflower',
    'Green Beans',
    'Green Peas',
    'Snow Peas',

    // ==========================================================
    // 11. FRUITS
    // ==========================================================
    'Local Mango',
    'Julie Mango',
    'Sheri Mango',
    'Ogbomosho Mango',
    'Green Mango',
    'Ripe Mango',
    'Semi-Ripe Mango',
    'Green Plantain',
    'Ripe Plantain',
    'Yellow Plantain',
    'Boli (Roasted Plantain)',
    'Dodo (Fried Plantain)',
    'Plantain Chips',
    'Green Banana',
    'Ripe Banana',
    'Sweet Banana',
    'Cavendish Banana',
    'Sweet Orange',
    'Bitter Orange',
    'Valencia Orange',
    'Navel Orange',
    'Tangerine',
    'Mandarin',
    'Fresh Lemon',
    'Fresh Lime',
    'Key Lime',
    'Fresh Pineapple',
    'Sweet Pineapple',
    'Fresh Watermelon',
    'Seedless Watermelon',
    'Red Watermelon',
    'Fresh Pawpaw',
    'Papaya',
    'Green Papaya',
    'Ripe Papaya',
    'Avocado Pear',
    'Avocado (Hass)',
    'Fresh Guava',
    'White Guava',
    'Pink Guava',
    'Fresh Coconut',
    'Young Coconut',
    'Mature Coconut',
    'Coconut Water',
    'Coconut Meat',
    'Fresh Soursop',
    'Soursop Juice',
    'Cashew Fruit',
    'Cashew Apple',
    'Cashew Nut',
    'Roasted Cashew',
    'African Pear',
    'Ube (African Pear)',
    'Fresh Apple',
    'Green Apple',
    'Red Apple',
    'Granny Smith',
    'Gala Apple',
    'Green Grapes',
    'Red Grapes',
    'Black Grapes',
    'Seedless Grapes',
    'Fresh Strawberry',
    'Frozen Strawberry',
    'Raspberry',
    'Blackberry',
    'Pomegranate',
    'Passion Fruit',
    'Star Fruit',
    'Dragon Fruit',
    'Date Fruit',
    'Fresh Figs',
    'Dried Figs',
    'Apricot',
    'Dried Apricots',
    'Fresh Peach',
    'Fresh Plum',
    'Dried Plums',
    'Cherry',
    'African Star Apple',
    'Agbalumo',
    'Udara',
    'Local Cherry',
    'Bush Mango',
    'Dika',
    'Ogbono (African Bush Mango)',
    'Cranberry',
    'Blueberry',
    'Gooseberry',

    // ==========================================================
    // 12. FLOURS & BAKING
    // ==========================================================
    'All Purpose Flour',
    'Bread Flour',
    'Cake Flour',
    'Pastry Flour',
    'Whole Wheat Flour',
    'Whole Grain Flour',
    'Gluten Free Flour',
    'Rice Flour',
    'Corn Flour',
    'Beans Flour',
    'Soy Flour',
    'Peanut Flour',
    'Cassava Flour',
    'Plantain Flour',
    'Coconut Flour',
    'Almond Flour',
    'Oat Flour',
    'Barley Flour',
    'Rye Flour',
    'Spelt Flour',
    'Sorghum Flour',
    'Semolina Flour',
    'Semovita',
    'Fufu Flour',
    'Amala Flour',
    'Lafun Flour',
    'Garri Flour',
    'Baking Powder',
    'Baking Soda',
    'Yeast',
    'Instant Yeast',
    'Active Dry Yeast',
    'Cornstarch',
    'Arrowroot Powder',
    'Tapioca Starch',
    'Potato Starch',
    'Xanthan Gum',
    'Guar Gum',

    // ==========================================================
    // 13. DAIRY & EGGS
    // ==========================================================
    'Fresh Milk',
    'Cow Milk',
    'Goat Milk',
    'Sheep Milk',
    'Powdered Milk',
    'Peak Milk',
    'Three Crowns Milk',
    'Nido Milk',
    'Condensed Milk',
    'Sweetened Condensed Milk',
    'Milkmaid',
    'Evaporated Milk',
    'Unsweetened Evaporated Milk',
    'Salted Butter',
    'Unsalted Butter',
    'Clarified Butter',
    'Local Cheese',
    'Wara',
    'Feta Cheese',
    'Processed Cheese',
    'Plain Yogurt',
    'Flavored Yogurt',
    'Greek Yogurt',
    'Fresh Eggs',
    'Fertilized Eggs',
    'Unfertilized Eggs',
    'Duck Eggs',
    'Quail Eggs',
    'Turkey Eggs',
    'Heavy Cream',
    'Sour Cream',
    'Cream Cheese',

    // ==========================================================
    // 14. BEVERAGES
    // ==========================================================
    'Coca-Cola',
    'Pepsi',
    'Fanta',
    'Sprite',
    '7 Up',
    'Mountain Dew',
    'Mirinda',
    'La Casera',
    'Chapman',
    'Zobo',
    'Hibiscus Tea',
    'Sobolo',
    'Bissap',
    'Zobo Drink',
    'Kunun Zaki',
    'Kunun Tsamiya',
    'Kunun Gyeda',
    'Palm Wine',
    'Ogoro',
    'Emu',
    'Pito',
    'Burukutu',
    'Local Beer',
    'Orange Juice',
    'Pineapple Juice',
    'Apple Juice',
    'Mango Juice',
    'Passion Fruit Juice',
    'Coconut Juice',
    'Soy Milk',
    'Almond Milk',
    'Black Tea',
    'Green Tea',
    'Chai Tea',
    'Herbal Tea',
    'Instant Coffee',
    'Ground Coffee',
    'Cappuccino',
    'Espresso',
    'Milo',
    'Bournvita',
    'Ovaltine',
    'Cocoa',
    'Hot Chocolate',

    // ==========================================================
    // 15. TRADITIONAL NIGERIAN FOODS
    // ==========================================================
    'Jollof Rice',
    'Fried Rice',
    'Coconut Rice',
    'Rice and Beans',
    'Ofada Rice',
    'Abakaliki Rice',
    'Rice and Stew',
    'Pounded Yam',
    'Pounded Yam (Fresh)',
    'Pounded Yam (Powder)',
    'Amala',
    'Amala (Yellow)',
    'Amala (Brown)',
    'Amala and Ewedu',
    'Eba',
    'Eba and Soup',
    'Fufu',
    'Fufu (Cassava)',
    'Fufu (Plantain)',
    'Fufu (Corn)',
    'Semo',
    'Semolina (Semo)',
    'Semo and Egusi',
    'Egusi Soup',
    'Egusi Melon Soup',
    'Egusi and Bitter Leaf',
    'Ogbono Soup',
    'Ogbono and Okra',
    'Ogbono and Egusi',
    'Okra Soup',
    'Okra and Ogbono',
    'Okro and Stew',
    'Ewedu Soup',
    'Ewedu and Amala',
    'Ewedu and Beans',
    'Efo Riro',
    'Efo Riro (Vegetable Soup)',
    'Efo Riro and Stew',
    'Bitter Leaf Soup',
    'Bitter Leaf and Egusi',
    'Bitter Leaf and Ogbono',
    'Catfish Pepper Soup',
    'Chicken Pepper Soup',
    'Goat Meat Pepper Soup',
    'Pepper Soup Spice',
    'Yam Pottage',
    'Asaro',
    'Yam and Beans',
    'Yam and Egg',
    'Akara (Beans Cake)',
    'Moimoi (Beans Pudding)',
    'Olele (Beans Balls)',
    'Gbegiri (Beans Soup)',
    'Abula',
    'Ewedu with Beans',
    'Olowo',
    'Agidi',
    'Ekuru',
    'Ogi (Pap)',
    'Akamu (Pap)',
    'Koko',
    'Oatmeal (Koko)',
    'Custard (Koko)',
    'Moin Moin',
    'Moi Moi (Fish)',
    'Moin Moin (Egg)',

    // ==========================================================
    // 16. STREET FOODS & SNACKS
    // ==========================================================
    'Beef Suya',
    'Chicken Suya',
    'Fish Suya',
    'Ram Suya',
    'Suya Spice',
    'Suya Pepper',
    'Masa',
    'Masa (Rice Cake)',
    'Dan Wake',
    'Danwake',
    'Danwake and Pepper',
    'Kilishi',
    'Kilishi (Dried Meat)',
    'Kilishi (Beef)',
    'Kilishi (Ram)',
    'Balango',
    'Balango (Dried Fish)',
    'Boli (Roasted Plantain)',
    'Akara (Fried Beans Cake)',
    'Akara and Pap',
    'Puff Puff',
    'Puff Puff and Sugar',
    'Puff Puff and Chocolate',
    'Buns',
    'Doughnuts',
    'Glazed Doughnuts',
    'Meat Pie',
    'Chicken Pie',
    'Fish Pie',
    'Sausage Roll',
    'Spring Roll',
    'Samosa',
    'Bread Roll',
    'Chin Chin',
    'Kuli Kuli',
    'Kokoro',
    'Plantain Chips',
    'Yam Chips',
    'Potato Chips',
    'Cassava Chips',
    'Groundnut Cake',
    'Peanut Brittle',
    'Coconut Candy',
    'Caramelized Plantain',
    'Coconut Chips',
    'Tiger Nut Candy',
    'Corn on the Cob',
    'Roasted Corn',
    'Boiled Corn',
    'Roasted Groundnut',
    'Boiled Groundnut',

    // ==========================================================
    // 17. PROCESSED & PACKAGED FOODS (UPDATED)
    // ==========================================================
    'Indomie Noodles',
    'Indomie Noodles (Chicken)',
    'Indomie Noodles (Beef)',
    'Indomie Noodles (Pepper)',
    'Indomie Noodles (Shrimp)',
    'Indomie Noodles (Spicy)',
    'Indomie Noodles (Onion)',
    'Indomie Noodles (Curry)',
    'Indomie Noodles (Vegetable)',
    'Indomie Noodles (Super Pack)',
    'Indomie Noodles (Jumbo Pack)',
    'Indomie Noodles (Family Pack)',
    'Indomie Noodles (70g)',
    'Indomie Noodles (100g)',
    'Indomie Noodles (120g)',
    'Indomie Noodles (200g)',
    'Indomie Instant Noodles',
    'Indomie Cup Noodles',
    'Indomie Cup Noodles (Chicken)',
    'Indomie Cup Noodles (Beef)',
    'Indomie Cup Noodles (Pepper)',
    'Indomie Cup Noodles (Shrimp)',
    'Indomie Mi Goreng',
    'Indomie Mi Goreng (Original)',
    'Indomie Mi Goreng (Spicy)',
    'Indomie Mi Goreng (BBQ)',
    'Indomie Mi Goreng (Satay)',
    'Indomie Mi Goreng (Hot & Spicy)',
    'Honeywell Noodles',
    'Honeywell Noodles (Chicken)',
    'Honeywell Noodles (Beef)',
    'Honeywell Noodles (Pepper)',
    'Honeywell Noodles (Shrimp)',
    'Honeywell Cup Noodles',
    'Dufil Noodles',
    'Dufil Noodles (Chicken)',
    'Dufil Noodles (Beef)',
    'Dufil Noodles (Pepper)',
    'Dufil Cup Noodles',
    'Instant Noodles (Chicken)',
    'Instant Noodles (Beef)',
    'Instant Noodles (Pepper)',
    'Instant Noodles (Shrimp)',
    'Instant Noodles (Spicy)',
    'Instant Cup Noodles',
    'Instant Cup Noodles (Chicken)',
    'Instant Cup Noodles (Beef)',
    'Instant Cup Noodles (Pepper)',
    'Noodles (Chicken Flavor)',
    'Noodles (Beef Flavor)',
    'Noodles (Pepper Flavor)',
    'Noodles (Shrimp Flavor)',
    'Noodles (Vegetable Flavor)',
    'Noodles (Curry Flavor)',
    'Noodles (Onion Flavor)',
    'Noodles (Spicy Flavor)',
    'Cup Noodles',
    'Cup Noodles (Chicken)',
    'Cup Noodles (Beef)',
    'Cup Noodles (Pepper)',
    'Cup Noodles (Shrimp)',
    'Cup Noodles (Spicy)',
    'Cup Noodles (Vegetable)',
    'Spaghetti',
    'Spaghetti Pasta',
    'Macaroni',
    'Pasta',
    'Tagliatelle',
    'Fettuccine',
    'Penne',
    'Fusilli',
    'Lasagna Sheets',
    'Ravioli',
    'Tortellini',
    'Cannelloni',
    'Ziti',
    'Linguine',
    'Orzo',
    'Milo Powder',
    'Milo Beverage',
    'Custard',
    'Powdered Custard',
    'Cornflakes',
    'Golden Morn',
    'Oatmeal',
    'Quaker Oats',
    'White Bread',
    'Brown Bread',
    'Wheat Bread',
    'Multigrain Bread',
    'Burger Buns',
    'Hot Dog Buns',
    'Croissant',
    'Pain au Chocolat',
    'Toast Bread',
    'Sandwich Bread',
    'Breadcrumbs',
    'Bread Rolls',
    'Bagel',
    'Pretzel',
    'Cake Flour',
    'Bread Flour',
    'Pastry Flour',

    // ==========================================================
    // 18. NUTS & SEEDS
    // ==========================================================
    'Peanuts',
    'Raw Groundnut',
    'Roasted Groundnut',
    'Salted Groundnut',
    'Cashew Nut (Raw)',
    'Cashew Nut (Roasted)',
    'Cashew Nut (Salted)',
    'Almonds',
    'Walnuts',
    'Pecans',
    'Brazil Nuts',
    'Macadamia',
    'Pistachios',
    'Hazelnuts',
    'Dried Coconut',
    'Sesame Seeds',
    'Sunflower Seeds',
    'Pumpkin Seeds',
    'Flax Seeds',
    'Chia Seeds',
    'Hemp Seeds',
    'Poppy Seeds',
    'Nigella Seeds',
    'Fenugreek Seeds',
    'Cumin Seeds',
    'Coriander Seeds',
    'Fennel Seeds',
    'Anise Seeds',
    'Cardamom Seeds',
    'Mustard Seeds',

    // ==========================================================
    // 19. DRY GOODS
    // ==========================================================
    'Dried Fish',
    'Dried Tilapia',
    'Dried Catfish',
    'Dried Mackerel',
    'Dried Herring',
    'Dried Crayfish',
    'Smoked Fish',
    'Smoked Tilapia',
    'Smoked Catfish',
    'Dried Meat',
    'Dried Beef',
    'Dried Goat',
    'Dried Snails',
    'Dried Shrimp',
    'Dried Prawns',
    'Dried Vegetables',
    'Dried Ugu',
    'Dried Bitter Leaf',
    'Dried Okra',
    'Dried Mushroom',
    'Dried Tomatoes',
    'Dried Pepper',
    'Dried Chili',
    'Dried Ginger',
    'Dried Garlic',
    'Dried Onion',
    'Kilishi (Beef)',
    'Kilishi (Ram)',
    'Balango (Dried Fish)',

    // ==========================================================
    // 20. FROZEN FOODS
    // ==========================================================
    'Frozen Chicken',
    'Frozen Turkey',
    'Frozen Duck',
    'Frozen Fish',
    'Frozen Tilapia',
    'Frozen Catfish',
    'Frozen Mackerel',
    'Frozen Prawns',
    'Frozen Shrimps',
    'Frozen Vegetables',
    'Frozen Peas',
    'Frozen Corn',
    'Frozen Mixed Vegetables',
    'Frozen Spinach',
    'Frozen Fruits',
    'Frozen Mango',
    'Frozen Pineapple',
    'Frozen Strawberries',
    'Frozen Blueberries',
    'Ice Cream',
    'Gelato',
    'Sorbet',
    'Frozen Yogurt',
    'Frozen Popsicles',
    'Frozen Juice',

    // ==========================================================
    // 21. HEALTH & ORGANIC
    // ==========================================================
    'Organic Rice',
    'Organic Beans',
    'Organic Vegetables',
    'Organic Fruits',
    'Organic Eggs',
    'Organic Chicken',
    'Organic Meat',
    'Organic Fish',
    'Organic Olive Oil',
    'Organic Coconut Oil',
    'Organic Sugar',
    'Organic Honey',
    'Organic Tea',
    'Organic Coffee',
    'Kale',
    'Quinoa',
    'Chia Seeds',
    'Flax Seeds',
    'Hemp Seeds',
    'Pumpkin Seeds',
    'Sunflower Seeds',
    'Sesame Seeds',
    'Spirulina',
    'Moringa',
    'Moringa Powder',
    'Moringa Leaves',
    'Tiger Nuts',
    'Tigernut Flour',
    'Tigernut Milk',
    'Protein Smoothie',
    'Green Smoothie',
    'Smoothie',
    'Soya Milk',
    'Almond Milk',

    // ==========================================================
    // 22. BABY FOOD & DIETARY
    // ==========================================================
    'Baby Cereal',
    'Baby Rice Cereal',
    'Baby Oatmeal',
    'Baby Food (Puree)',
    'Baby Formula',
    'Infant Formula',
    'Toddler Snacks',
    'Teething Biscuits',
    'Baby Custard',
    'Gluten Free Flour',
    'Gluten Free Pasta',
    'Gluten Free Bread',
    'Gluten Free Cereal',
    'Low Sodium',
    'Low Fat',
    'Low Sugar',
    'Sugar Free',
    'Protein Powder',
    'Whey Protein',
    'Plant Protein',
    'Meal Replacement',
    'Diet Shake',
    'Weight Loss Snack',
    'Energy Bar',
    'Protein Bar',
    'Fitness Snack',

    // ==========================================================
    // 23. NIGERIAN MARKET STAPLES
    // ==========================================================
    'Ijebu Garri',
    'Benue Garri',
    'Abakaliki Rice',
    'Ofada Rice',
    'Ebonyi Rice',
    'Egusi (Melon)',
    'Ogbono (Wild Mango)',
    'Uziza Leaf',
    'Scent Leaf',
    'Efirin',
    'Bitter Leaf (Fresh)',
    'Ugu Leaf',
    'Waterleaf',
    'Ewedu Leaf',
    'Efo (Amaranth)',
    'Local Spices',
    'Pepper (Local)',
    'Dry Pepper (Local)',
    'Ogiri (Locust Bean)',
    'Iru (Locust Bean)',
    'Crayfish (Local)',
    'Stockfish (Imported)',
    'Palm Oil (Local)',
    'Groundnut Oil (Local)',
    'Palm Wine (Fresh)',
    'Zobo Leaves',
    'Kunun Zaki (Local)',
    'Pito (Local Beer)',
    'Local Honey',
    'Shea Butter (Local)',
    'Locust Bean (Dried)',
    'Mudu',
    'Kobo',
    'Kongu',
    'Egbame',
    'Igba',
    'Igabale',
    'Akara',
    'Oju',
    'Kongo',
    'Idigbo',
    'Aje',
    'Eku',
    'Okete',
    'Iyan',
    'Ofe',
    'Ofu',
    'Atuko',
    'Eran',
    'Omi',
    'Odo',
    'Igi',
    'Omo',
    'Oko',
    'Oya',
    'Dudu',
    'Pupa',
    'Funfun',
    'Awor'
];