// ============================================================
// COMMON UNITS (Fallback if none in Firebase) - 500+ Units
// ============================================================

    export const commonUnits = [
 
    // ==========================================================
    // 1. WEIGHT (Kg, g, tonnes)
    // ==========================================================
    '100kg bag', '50kg bag', '50kg sack', '50kg jute bag', '50kg poly bag',
    '25kg bag', '25kg sack', '25kg jute bag', '25kg poly bag',
    '10kg bag', '10kg sack', '10kg jute bag', '10kg poly bag',
    '5kg bag', '5kg sack', '5kg jute bag', '5kg poly bag',
    '2kg bag', '2kg pack', '2kg sack',
    '1kg bag', '1kg pack', '1kg sack',
    '500g pack', '500g bag', '500g sachet',
    '250g pack', '250g bag', '250g sachet',
    '100g pack', '100g bag', '100g sachet',
    '50g pack', '50g bag', '50g sachet',
    '25g pack', '25g sachet',
    '10g pack', '10g sachet',
    '5g pack', '5g sachet',
    'kg', 'kilogram', 'kilo', 
    'gram', 'g', 'mg', 'milligram',
    'tonne', 'metric tonne', 'ton', 
    'pound', 'lb', 'ounce', 'oz',
    'stone', 'quarter', 'half pound',
    'bushel', 'peck', 'hundredweight',
    
    // ==========================================================
    // 2. VOLUME (Liters, ml, gallons)
    // ==========================================================
    '20 liters', '20L', '20L jerrycan', '20L keg',
    '10 liters', '10L', '10L jerrycan', '10L keg',
    '5 liters', '5L', '5L gallon', '5L jerrycan',
    '4 liters', '4L', '4L gallon',
    '3 liters', '3L', '3L gallon',
    '2 liters', '2L', '2L bottle', '2L container',
    '1 liter', '1L', '1L bottle', '1L container',
    '750ml', '75cl', '75cl bottle',
    '700ml', '70cl', '70cl bottle',
    '600ml', '60cl', '60cl bottle',
    '500ml', '50cl', '50cl bottle', 'half litre',
    '400ml', '40cl', '40cl bottle',
    '330ml', '33cl', '33cl can', '33cl bottle',
    '300ml', '30cl', '30cl bottle',
    '250ml', '25cl', '25cl bottle', 'quarter litre',
    '200ml', '20cl', '20cl bottle', '200ml sachet',
    '150ml', '15cl', '15cl bottle',
    '100ml', '10cl', '10cl bottle', '100ml sachet',
    '50ml', '5cl', '5cl bottle', 'mini bottle',
    'gallon', 'gallon (4L)', 'gallon (5L)',
    'gallon (3L)', 'gallon (2.5L)',
    'jerrycan', 'jerrycan (25L)', 'jerrycan (30L)',
    'jerrycan (50L)', 'jerrycan (100L)',
    'drum', 'drum (200L)', 'drum (250L)',
    'drum (100L)', 'drum (50L)',
    'barrel', 'barrel (200L)', 'barrel (160L)',
    'keg', 'keg (50L)', 'keg (30L)',
    'keg (20L)', 'keg (10L)',
    'bucket', 'bucket (20L)', 'bucket (15L)',
    'bucket (10L)', 'bucket (5L)',
    'bowl', 'bowl (large)', 'bowl (medium)',
    'bowl (small)', 'cup', 'cup (large)',
    'cup (medium)', 'cup (small)',
    'pint', 'quart', 'millilitre', 'ml',
    'fluid ounce', 'fl oz', 'imperial gallon',
    
    // ==========================================================
    // 3. PACKAGING (Cartons, crates, packs)
    // ==========================================================
    'carton (6 packs)', 'carton (6 bottles)', 'carton (6 cans)',
    'carton (12 packs)', 'carton (12 bottles)', 'carton (12 cans)',
    'carton (24 packs)', 'carton (24 bottles)', 'carton (24 cans)',
    'carton (48 packs)', 'carton (48 bottles)', 'carton (48 cans)',
    'carton (100 packs)', 'carton (100 sachets)', 'carton (100 pieces)',
    'carton (144 pieces)', 'carton (144 packs)',
    'carton (200 pieces)', 'carton (200 packs)',
    'carton (500 pieces)', 'carton (500 packs)',
    'crate (6)', 'crate (9)', 'crate (12)',
    'crate (20)', 'crate (24)', 'crate (30)',
    'crate (36)', 'crate (48)', 'crate (50)',
    'crate (60)', 'crate (72)', 'crate (100)',
    'crate (144)', 'crate (200)',
    'pack', 'pack (6)', 'pack (12)', 'pack (24)',
    'pack (36)', 'pack (48)', 'pack (50)',
    'pack (72)', 'pack (96)', 'pack (100)',
    'pack (144)', 'pack (200)', 'pack (500)',
    'sachet', 'sachet (10)', 'sachet (20)', 'sachet (25)',
    'sachet (50)', 'sachet (100)', 'sachet (200)',
    'sachet (500)', 'sachet (1000)',
    'bottle', 'bottle (6)', 'bottle (12)', 'bottle (24)',
    'bottle (36)', 'bottle (48)', 'bottle (50)',
    'bottle (72)', 'bottle (100)', 'bottle (144)',
    'can', 'can (6)', 'can (12)', 'can (24)',
    'can (30)', 'can (36)', 'can (48)',
    'can (50)', 'can (72)', 'can (100)',
    'can (144)', 'can (200)',
    'tin', 'tin (6)', 'tin (12)', 'tin (24)',
    'tin (36)', 'tin (48)', 'tin (50)',
    'tin (72)', 'tin (96)', 'tin (100)',
    'tin (144)', 'tin (200)',
    'box', 'box (6)', 'box (10)', 'box (12)',
    'box (20)', 'box (24)', 'box (36)',
    'box (48)', 'box (50)', 'box (72)',
    'box (96)', 'box (100)', 'box (144)',
    'box (200)', 'box (500)',
    'bag (small)', 'bag (medium)', 'bag (large)',
    'bag (jumbo)', 'bag (mini)',
    'sack', 'sack (small)', 'sack (medium)',
    'sack (large)', 'sack (jumbo)',
    'jute bag', 'jute bag (small)', 'jute bag (large)',
    'poly bag', 'poly bag (small)', 'poly bag (large)',
    'container', 'container (20ft)', 'container (40ft)',
    'container (40ft HC)', 'container (45ft)',
    'container (53ft)', 'container (reefer)',
    'pallet', 'pallet (20)', 'pallet (30)', 'pallet (50)',
    'pallet (100)', 'pallet (200)', 'pallet (500)',
    'pallet (1000)', 'pallet (2000)',
    'flat', 'flat (6)', 'flat (10)', 'flat (12)',
    'flat (24)', 'flat (36)', 'flat (48)',
    'flat (72)', 'flat (100)', 'flat (144)',
    'tote', 'tote (50)', 'tote (100)', 'tote (200)',
    'tote (500)', 'tote (1000)', 'tote (2000)',
    'wrapper', 'wrapper (small)', 'wrapper (medium)',
    'wrapper (large)', 'wrapper (jumbo)',
    'packet', 'packet (small)', 'packet (medium)',
    'packet (large)', 'packet (jumbo)',
    'sleeve', 'sleeve (5)', 'sleeve (10)',
    'sleeve (25)', 'sleeve (50)',
    
    // ==========================================================
    // 4. COUNT & QUANTITY
    // ==========================================================
    'unit', 'piece', 'pcs',
    'pieces (2)', 'pieces (3)', 'pieces (4)',
    'pieces (5)', 'pieces (6)', 'pieces (8)',
    'pieces (10)', 'pieces (12)', 'pieces (15)',
    'pieces (20)', 'pieces (24)', 'pieces (25)',
    'pieces (30)', 'pieces (36)', 'pieces (40)',
    'pieces (48)', 'pieces (50)', 'pieces (60)',
    'pieces (72)', 'pieces (80)', 'pieces (96)',
    'pieces (100)', 'pieces (120)', 'pieces (144)',
    'pieces (150)', 'pieces (180)', 'pieces (200)',
    'pieces (250)', 'pieces (300)', 'pieces (360)',
    'pieces (400)', 'pieces (450)', 'pieces (500)',
    'pieces (600)', 'pieces (720)', 'pieces (800)',
    'pieces (1000)', 'pieces (1200)', 'pieces (1440)',
    'pieces (1500)', 'pieces (1800)', 'pieces (2000)',
    'dozen', 'half dozen', 'dozen (6)', 'dozen (12)',
    'dozen (20)', 'dozen (24)', 'dozen (36)',
    'dozen (48)', 'dozen (50)', 'dozen (72)',
    'dozen (96)', 'dozen (100)', 'dozen (144)',
    'dozen (200)', 'dozen (500)',
    'gross (144)', 'gross (1728)', 'great gross',
    'score (20)', 'score (100)',
    'bunch', 'bunch (small)', 'bunch (medium)',
    'bunch (large)', 'bunch (jumbo)',
    'bunch (5)', 'bunch (10)', 'bunch (20)',
    'bunch (50)', 'bunch (100)',
    'basket', 'basket (small)', 'basket (medium)',
    'basket (large)', 'basket (jumbo)',
    'basket (5)', 'basket (10)', 'basket (20)',
    'basket (50)', 'basket (100)',
    'heap', 'heap (small)', 'heap (medium)',
    'heap (large)', 'heap (jumbo)',
    'bundle', 'bundle (5)', 'bundle (10)',
    'bundle (20)', 'bundle (25)', 'bundle (50)',
    'bundle (100)', 'bundle (200)',
    'handful', 'handful (small)', 'handful (medium)',
    'handful (large)', 'handful (jumbo)',
    'stick', 'stick (5)', 'stick (10)',
    'stick (20)', 'stick (50)', 'stick (100)',
    'roll', 'roll (6)', 'roll (12)', 'roll (24)',
    'roll (48)', 'roll (50)', 'roll (100)',
    'roll (144)', 'roll (200)',
    'ream', 'ream (500 sheets)', 'ream (1000 sheets)',
    'sheet', 'sheet (10)', 'sheet (20)',
    'sheet (50)', 'sheet (100)', 'sheet (500)',
    'sheet (1000)',
    'set', 'set (2)', 'set (3)', 'set (4)',
    'set (5)', 'set (6)', 'set (8)',
    'set (10)', 'set (12)', 'set (20)',
    'set (24)', 'set (48)',
    'pair', 'pair (2)', 'pair (3)', 'pair (4)',
    'pair (5)', 'pair (6)', 'pair (10)',
    'pair (12)', 'pair (24)', 'pair (48)',
    'pair (50)', 'pair (100)',
    'tray', 'tray (6)', 'tray (10)', 'tray (12)',
    'tray (20)', 'tray (24)', 'tray (36)',
    'tray (48)', 'tray (50)', 'tray (72)',
    'tray (96)', 'tray (100)', 'tray (144)',
    
    // ==========================================================
    // 5. NIGERIAN MARKET UNITS (Traditional)
    // ==========================================================
    // --- Containers ---
    'paint rubber', 'paint rubber (small)', 'paint rubber (medium)',
    'paint rubber (large)', 'paint rubber (jumbo)',
    'tin rubber', 'tin rubber (small)', 'tin rubber (medium)',
    'tin rubber (large)', 'tin rubber (jumbo)',
    'small bowl', 'medium bowl', 'big bowl', 'jumbo bowl',
    'mudu (small)', 'mudu (medium)', 'mudu (large)',
    'mudu (jumbo)', 'olina', 'olina (small)',
    'olina (medium)', 'olina (large)', 'olina (jumbo)',
    'derica', 'derica (small)', 'derica (medium)',
    'derica (large)', 'derica (jumbo)',
    'congo', 'congo (small)', 'congo (medium)',
    'congo (large)', 'congo (jumbo)',
    'rubber', 'rubber (small)', 'rubber (medium)',
    'rubber (large)', 'rubber (jumbo)',
    'basin', 'basin (small)', 'basin (medium)',
    'basin (large)', 'basin (jumbo)',
    'plate', 'plate (small)', 'plate (medium)',
    'plate (large)', 'plate (jumbo)',
    'saucer', 'saucer (small)', 'saucer (large)',
    'cup (measuring)', 'cup (small)', 'cup (large)',
    
    // --- Traditional Measures ---
    'mudu', 'kobo', 'kongu', 'egbame',
    'igba', 'igbale', 'akara', 'oju',
    'kongo', 'idigbo', 'aje', 'eku',
    'okete', 'iyan', 'ofe', 'ofu',
    'atuko', 'eran', 'omi', 'odo',
    'igi', 'omo', 'oko', 'oya',
    'dudu', 'pupa', 'funfun', 'awor',
    'oko (field)', 'odo (river)', 'omi (water)',
    'aje (wealth)', 'okete (big)', 'eku (small)',
    
    // ==========================================================
    // 6. FOOD SPECIFIC UNITS
    // ==========================================================
    // --- Grains ---
    'cup (rice)', 'cup (beans)', 'cup (millet)',
    'cup (guinea corn)', 'cup (wheat)',
    'mudu (rice)', 'mudu (beans)', 'mudu (millet)',
    'mudu (guinea corn)', 'mudu (wheat)',
    'paint rubber (rice)', 'paint rubber (beans)',
    'paint rubber (millet)', 'paint rubber (guinea corn)',
    'congo (rice)', 'congo (beans)', 'congo (millet)',
    'congo (guinea corn)', 'congo (wheat)',
    'derica (rice)', 'derica (beans)', 'derica (millet)',
    'derica (guinea corn)', 'derica (wheat)',
    'olina (rice)', 'olina (beans)', 'olina (millet)',
    'olina (guinea corn)', 'olina (wheat)',
    'bowl (rice)', 'bowl (beans)', 'bowl (millet)',
    'bowl (guinea corn)', 'bowl (wheat)',
    'bag (rice)', 'bag (beans)', 'bag (millet)',
    'bag (guinea corn)', 'bag (wheat)',
    
    // --- Vegetables ---
    'bundle (ugu)', 'bundle (spinach)', 'bundle (waterleaf)',
    'bundle (bitter leaf)', 'bundle (efo)',
    'bundle (amaranth)', 'bundle (celery)',
    'bundle (lettuce)', 'bundle (cabbage)',
    'bunch (ugu)', 'bunch (spinach)', 'bunch (waterleaf)',
    'bunch (bitter leaf)', 'bunch (efo)',
    'heap (ugu)', 'heap (spinach)', 'heap (waterleaf)',
    'heap (bitter leaf)', 'heap (efo)',
    'basket (ugu)', 'basket (spinach)', 'basket (waterleaf)',
    'basket (bitter leaf)', 'basket (efo)',
    'stick (ugu)', 'stick (spinach)', 'stick (waterleaf)',
    'stick (bitter leaf)', 'stick (efo)',
    'handful (ugu)', 'handful (spinach)',
    'handful (waterleaf)', 'handful (bitter leaf)',
    
    // --- Fruits ---
    'piece (orange)', 'piece (mango)', 'piece (banana)',
    'piece (plantain)', 'piece (pineapple)',
    'piece (avocado)', 'piece (apple)', 'piece (pear)',
    'piece (guava)', 'piece (cashew)', 'piece (coconut)',
    'piece (watermelon)', 'piece (pawpaw)',
    'piece (soursop)', 'piece (passion fruit)',
    'pieces (orange)', 'pieces (mango)', 'pieces (banana)',
    'pieces (plantain)', 'pieces (pineapple)',
    'bunch (banana)', 'bunch (plantain)',
    'bunch (orange)', 'bunch (mango)',
    'dozen (orange)', 'dozen (mango)', 'dozen (banana)',
    'dozen (plantain)', 'dozen (pineapple)',
    'bag (orange)', 'bag (mango)', 'bag (banana)',
    'bag (plantain)', 'bag (pineapple)',
    'basket (orange)', 'basket (mango)', 'basket (banana)',
    'basket (plantain)', 'basket (pineapple)',
    'handful (groundnut)', 'handful (cashew)',
    'handful (coconut)', 'handful (guava)',
    'bag (groundnut)', 'bag (cashew)', 'bag (coconut)',
    'bag (guava)', 'bag (avocado)',
    
    // --- Fish ---
    'piece (fish)', 'piece (stockfish)', 'piece (tilapia)',
    'piece (mackerel)', 'piece (catfish)',
    'piece (crayfish)', 'piece (prawn)',
    'piece (shrimp)', 'piece (snail)',
    'small fish', 'medium fish', 'big fish',
    'large fish', 'jumbo fish', 'whole fish',
    'whole stockfish', 'whole mackerel',
    'whole tilapia', 'whole catfish',
    'kg (fish)', 'kg (stockfish)', 'kg (mackerel)',
    'kg (tilapia)', 'kg (catfish)',
    'kg (crayfish)', 'kg (prawn)',
    'kg (shrimp)', 'kg (snail)',
    'bag (fish)', 'bag (stockfish)', 'bag (mackerel)',
    'bag (tilapia)', 'bag (catfish)',
    'bag (crayfish)', 'bag (prawn)',
    'bag (shrimp)', 'bag (snail)',
    'dozen (fish)', 'dozen (stockfish)',
    'dozen (mackerel)', 'dozen (tilapia)',
    'basket (fish)', 'basket (stockfish)',
    'basket (mackerel)', 'basket (tilapia)',
    'basket (catfish)', 'basket (crayfish)',
    
    // --- Meat ---
    'kg (beef)', 'kg (goat)', 'kg (chicken)',
    'kg (ram)', 'kg (turkey)', 'kg (duck)',
    'kg (pork)', 'kg (rabbit)', 'kg (snail)',
    'kg (bushmeat)', 'kg (grasscutter)',
    'piece (beef)', 'piece (goat)', 'piece (chicken)',
    'piece (ram)', 'piece (turkey)',
    'piece (pork)', 'piece (rabbit)',
    'whole chicken', 'whole turkey', 'whole duck',
    'whole ram', 'whole goat', 'whole rabbit',
    'whole bushmeat', 'whole grasscutter',
    'cut (beef)', 'cut (goat)', 'cut (chicken)',
    'cut (ram)', 'cut (turkey)', 'cut (pork)',
    'portion (beef)', 'portion (goat)',
    'portion (chicken)', 'portion (ram)',
    'leg (chicken)', 'leg (turkey)',
    'thigh (chicken)', 'thigh (turkey)',
    'breast (chicken)', 'breast (turkey)',
    'wing (chicken)', 'wing (turkey)',
    
    // --- Oils ---
    'litre (oil)', 'litre (palm oil)', 'litre (red oil)',
    'litre (groundnut oil)', 'litre (vegetable oil)',
    'litre (coconut oil)', 'litre (olive oil)',
    'litre (sunflower oil)', 'litre (sesame oil)',
    'gallon (oil)', 'gallon (palm oil)',
    'gallon (groundnut oil)', 'gallon (vegetable oil)',
    'gallon (coconut oil)', 'gallon (olive oil)',
    'jerrycan (oil)', 'jerrycan (palm oil)',
    'jerrycan (groundnut oil)', 'jerrycan (vegetable oil)',
    'bottle (oil)', 'bottle (palm oil)',
    'bottle (groundnut oil)', 'bottle (vegetable oil)',
    'keg (oil)', 'keg (palm oil)',
    'keg (groundnut oil)', 'keg (vegetable oil)',
    'drum (oil)', 'drum (palm oil)',
    'drum (groundnut oil)', 'drum (vegetable oil)',
    'paint rubber (oil)', 'paint rubber (palm oil)',
    'tin rubber (oil)', 'tin rubber (palm oil)',
    'mudu (oil)', 'mudu (palm oil)',
    'olina (oil)', 'olina (palm oil)',
    
    // --- Spices & Seasonings ---
    'sachet (seasoning)', 'sachet (salt)', 'sachet (sugar)',
    'sachet (pepper)', 'sachet (curry)', 'sachet (thyme)',
    'sachet (nutmeg)', 'sachet (cinnamon)',
    'sachet (ginger)', 'sachet (garlic)',
    'pack (seasoning)', 'pack (salt)', 'pack (sugar)',
    'pack (pepper)', 'pack (curry)', 'pack (thyme)',
    'pack (nutmeg)', 'pack (cinnamon)',
    'pack (ginger)', 'pack (garlic)',
    'bag (salt)', 'bag (sugar)', 'bag (pepper)',
    'bag (seasoning)', 'bag (curry)', 'bag (thyme)',
    'tin (seasoning)', 'tin (salt)', 'tin (sugar)',
    'tin (pepper)', 'tin (curry)', 'tin (thyme)',
    'kg (salt)', 'kg (sugar)', 'kg (pepper)',
    'kg (seasoning)', 'kg (curry)', 'kg (thyme)',
    'kg (nutmeg)', 'kg (cinnamon)', 'kg (ginger)',
    'kg (garlic)',
    'bottle (seasoning)', 'bottle (salt)', 'bottle (sugar)',
    'bottle (pepper)', 'bottle (curry)', 'bottle (thyme)',
    'bottle (nutmeg)', 'bottle (cinnamon)',
    'bottle (ginger)', 'bottle (garlic)',
    
    // --- Beverages ---
    'carton (drinks)', 'carton (milo)', 'carton (milk)',
    'carton (beverages)', 'carton (juice)',
    'carton (soda)', 'carton (water)',
    'pack (drinks)', 'pack (milo)', 'pack (milk)',
    'pack (beverages)', 'pack (juice)',
    'pack (soda)', 'pack (water)',
    'bottle (drinks)', 'bottle (milo)', 'bottle (milk)',
    'bottle (beverages)', 'bottle (juice)',
    'bottle (soda)', 'bottle (water)',
    'can (drinks)', 'can (milo)', 'can (milk)',
    'can (beverages)', 'can (juice)',
    'can (soda)', 'can (water)',
    'sachet (milo)', 'sachet (milk)', 'sachet (beverages)',
    'sachet (juice)', 'sachet (water)',
    'tin (milo)', 'tin (milk)', 'tin (beverages)',
    'tin (juice)', 'tin (soda)',
    'kg (milo)', 'kg (milk)', 'kg (beverages)',
    'kg (juice)', 'kg (soda)',
    'bag (milo)', 'bag (milk)', 'bag (beverages)',
    'bag (juice)', 'bag (soda)',
    
    // ==========================================================
    // 7. LIQUIDS (Non-Oil)
    // ==========================================================
    'gallon (water)', 'gallon (beverage)',
    'gallon (drink)', 'gallon (juice)',
    'gallon (soda)', 'gallon (milk)',
    'bottle (water)', 'bottle (beverage)',
    'bottle (drink)', 'bottle (juice)',
    'bottle (soda)', 'bottle (milk)',
    'jerrycan (water)', 'jerrycan (beverage)',
    'jerrycan (drink)', 'jerrycan (juice)',
    'jerrycan (soda)', 'jerrycan (milk)',
    'sachet (water)', 'sachet (beverage)',
    'sachet (drink)', 'sachet (juice)',
    'sachet (soda)', 'sachet (milk)',
    'cup (beverage)', 'cup (drink)', 'cup (juice)',
    'cup (soda)', 'cup (milk)',
    'litre (water)', 'litre (beverage)',
    'litre (drink)', 'litre (juice)',
    'litre (soda)', 'litre (milk)',
    'drum (water)', 'drum (beverage)',
    'drum (drink)', 'drum (juice)',
    'drum (soda)', 'drum (milk)',
    'keg (water)', 'keg (beverage)',
    'keg (drink)', 'keg (juice)',
    'keg (soda)', 'keg (milk)',
    'bucket (water)', 'bucket (beverage)',
    'bucket (drink)', 'bucket (juice)',
    'bucket (soda)', 'bucket (milk)',
    
    // ==========================================================
    // 8. OTHER UNITS
    // ==========================================================
    'packet', 'packet (small)', 'packet (medium)',
    'packet (large)', 'packet (jumbo)',
    'packet (10)', 'packet (20)', 'packet (50)',
    'packet (100)', 'packet (200)', 'packet (500)',
    'wrapper', 'wrapper (small)', 'wrapper (medium)',
    'wrapper (large)', 'wrapper (jumbo)',
    'wrapper (10)', 'wrapper (20)', 'wrapper (50)',
    'wrapper (100)', 'wrapper (200)',
    'tray', 'tray (6)', 'tray (10)', 'tray (12)',
    'tray (20)', 'tray (24)', 'tray (30)',
    'tray (36)', 'tray (48)', 'tray (50)',
    'tray (60)', 'tray (72)', 'tray (96)',
    'tray (100)', 'tray (120)', 'tray (144)',
    'tray (150)', 'tray (180)', 'tray (200)',
    
    // ==========================================================
    // 9. MIXED / COMBINATION
    // ==========================================================
    'mixed', 'assorted', 'variety pack',
    'variety (6)', 'variety (12)', 'variety (24)',
    'variety (48)', 'variety (100)',
    'combo', 'combo (6)', 'combo (12)',
    'combo (24)', 'combo (36)', 'combo (48)',
    'combo (50)', 'combo (72)', 'combo (100)',
    'combo (144)', 'combo (200)',
    'sample', 'sample pack', 'trial pack',
    'trial (6)', 'trial (12)', 'trial (24)',
    'trial (48)', 'trial (100)',
    'starter pack', 'starter kit', 'gift pack',
    'gift set', 'gift set (6)', 'gift set (12)',
    'gift set (24)', 'gift set (48)',
    'hamper', 'hamper (small)', 'hamper (medium)',
    'hamper (large)', 'hamper (jumbo)',
    'hamper (6)', 'hamper (12)', 'hamper (24)',
    'hamper (48)', 'hamper (100)',
    
    // ==========================================================
    // 10. SERVICE-BASED & MISCELLANEOUS
    // ==========================================================
    'hour', 'day', 'week', 'month',
    'year', 'session', 'service', 'consultation',
    'hourly', 'daily', 'weekly', 'monthly',
    'annual', 'quarterly', 'biannual',
    'per session', 'per service', 'per consultation',
    'per hour', 'per day', 'per week',
    'per month', 'per year', 'per quarter',
    'per article', 'per post', 'per item',
    'per page', 'per word', 'per line',
    'per character', 'per second', 'per minute',
    'per hour (service)', 'per day (service)',
    'per week (service)', 'per month (service)',
    'flat rate', 'fixed rate', 'variable rate',
    'installment', 'monthly installment',
    'weekly installment', 'quarterly installment',
    'annual installment', 'per installment'
];